import type { BuildingType, Trait, TraitId, UnitTypeDef } from "./types";

export const TRAITS: Record<TraitId, Trait> = {
  brave: {
    id: "brave",
    name: "Brave",
    description: "Ne recule devant aucun combat.",
    effects: { martial: 3 },
  },
  cowardly: {
    id: "cowardly",
    name: "Lâche",
    description: "Fuit le danger, au grand dam de sa cour.",
    effects: { martial: -3 },
  },
  wise: {
    id: "wise",
    name: "Sage",
    description: "Voit loin et juge avec discernement.",
    effects: { stewardship: 2, diplomacy: 2 },
  },
  foolish: {
    id: "foolish",
    name: "Sot",
    description: "Prend des décisions hâtives.",
    effects: { stewardship: -2, diplomacy: -2 },
  },
  just: {
    id: "just",
    name: "Juste",
    description: "Le peuple respecte son sens de la justice.",
    effects: { diplomacy: 2, stewardship: 1 },
  },
  cruel: {
    id: "cruel",
    name: "Cruel",
    description: "Gouverne par la peur.",
    effects: { martial: 2, diplomacy: -3 },
  },
  generous: {
    id: "generous",
    name: "Généreux",
    description: "Sa cour et son peuple lui sont loyaux.",
    effects: { diplomacy: 2 },
  },
  greedy: {
    id: "greedy",
    name: "Avide",
    description: "Amasse plus qu'il ne redistribue.",
    effects: { stewardship: 2, diplomacy: -2 },
  },
  pious: {
    id: "pious",
    name: "Pieux",
    description: "La foi du peuple grandit sous son règne.",
    effects: { piety: 3 },
  },
  impious: {
    id: "impious",
    name: "Impie",
    description: "Se soucie peu des dieux.",
    effects: { piety: -3 },
  },
  charismatic: {
    id: "charismatic",
    name: "Charismatique",
    description: "Rassemble les foules par sa seule présence.",
    effects: { diplomacy: 3 },
  },
  frail: {
    id: "frail",
    name: "Fragile",
    description: "Sa santé décline plus vite que la normale.",
    effects: {},
  },
  hale: {
    id: "hale",
    name: "Robuste",
    description: "Un corps fait pour endurer les années.",
    effects: {},
  },
  ambitious: {
    id: "ambitious",
    name: "Ambitieux",
    description: "Ne se satisfait jamais de ce qu'il possède.",
    effects: { martial: 1, stewardship: 1 },
  },
};

export const BUILDINGS: Record<string, BuildingType> = {
  // --- Militaire : unités (puissance offensive) et défenses ---
  barracks: {
    id: "barracks",
    name: "Caserne",
    category: "military",
    age: "medieval",
    cost: 80,
    description: "Entraîne des troupes et renforce la puissance militaire.",
    effects: { martial: 4 },
  },
  arsenal: {
    id: "arsenal",
    name: "Arsenal",
    category: "military",
    age: "medieval",
    cost: 170,
    description: "Arme des troupes d'élite pour des campagnes offensives.",
    effects: { martial: 9 },
  },
  walls: {
    id: "walls",
    name: "Murailles",
    category: "military",
    age: "medieval",
    cost: 100,
    description: "Protège la province des invasions.",
    effects: { martial: 2, stability: 2, defense: 15 },
  },
  garrison: {
    id: "garrison",
    name: "Garnison",
    category: "military",
    age: "medieval",
    cost: 130,
    description: "Une garnison permanente qui défend la ville en cas de siège.",
    effects: { defense: 20, stability: 1 },
  },
  shipyard: {
    id: "shipyard",
    name: "Chantier naval",
    category: "military",
    age: "medieval",
    cost: 150,
    description: "Permet de recruter et d'équiper des forces navales.",
    effects: { martial: 3 },
  },
  arsenal_vapeur: {
    id: "arsenal_vapeur",
    name: "Arsenal à vapeur",
    category: "military",
    age: "steam",
    cost: 260,
    description: "Forge l'artillerie et les cuirassés propulsés à la vapeur.",
    effects: { martial: 14, defense: 10 },
  },
  aeroport: {
    id: "aeroport",
    name: "Aéroport militaire",
    category: "military",
    age: "modern",
    cost: 320,
    description: "Permet enfin de recruter et d'équiper le corps aérien.",
    effects: { martial: 8, defense: 8 },
  },
  base_orbitale: {
    id: "base_orbitale",
    name: "Base orbitale",
    category: "military",
    age: "future",
    cost: 420,
    description: "Projette la puissance du royaume jusque dans l'orbite d'Orion.",
    effects: { martial: 20, defense: 15 },
  },

  // --- Civil : habitations et production ---
  housing: {
    id: "housing",
    name: "Quartiers d'habitation",
    category: "civil",
    age: "medieval",
    cost: 75,
    description: "Loge davantage d'habitants et accélère la croissance.",
    effects: { populationGrowth: 0.015 },
  },
  farm: {
    id: "farm",
    name: "Champs cultivés",
    category: "civil",
    age: "medieval",
    cost: 40,
    description: "Augmente la production de nourriture.",
    effects: { food: 6 },
  },
  mine: {
    id: "mine",
    name: "Mine",
    category: "civil",
    age: "medieval",
    cost: 120,
    description: "Extrait des minerais précieux, source d'or régulière.",
    effects: { gold: 11 },
  },
  market: {
    id: "market",
    name: "Marché",
    category: "civil",
    age: "medieval",
    cost: 60,
    description: "Augmente les revenus en or.",
    effects: { gold: 5 },
  },
  factory: {
    id: "factory",
    name: "Manufacture",
    category: "civil",
    age: "medieval",
    cost: 210,
    description: "Produit en masse, au prix d'un peu de mécontentement.",
    effects: { gold: 20, stability: -1 },
  },
  usine_vapeur: {
    id: "usine_vapeur",
    name: "Usine à vapeur",
    category: "civil",
    age: "steam",
    cost: 240,
    description: "Multiplie la production grâce à la mécanisation à vapeur.",
    effects: { gold: 28, stability: -1 },
  },
  hopital: {
    id: "hopital",
    name: "Hôpital",
    category: "civil",
    age: "modern",
    cost: 260,
    description: "Soigne la population et accélère sa croissance.",
    effects: { populationGrowth: 0.02, stability: 2 },
  },
  reacteur_fusion: {
    id: "reacteur_fusion",
    name: "Réacteur à fusion",
    category: "civil",
    age: "future",
    cost: 400,
    description: "Une énergie quasi-illimitée pour le royaume.",
    effects: { gold: 40, food: 20 },
  },

  // --- Scientifique : savoir et innovation ---
  school: {
    id: "school",
    name: "École",
    category: "scientific",
    age: "medieval",
    cost: 95,
    description: "Instruit la population et stimule son développement.",
    effects: { populationGrowth: 0.01, gold: 3 },
  },
  laboratory: {
    id: "laboratory",
    name: "Laboratoire",
    category: "scientific",
    age: "medieval",
    cost: 190,
    description: "Fait progresser les connaissances et l'artisanat.",
    effects: { gold: 9, prestige: 3 },
  },
  observatory: {
    id: "observatory",
    name: "Observatoire",
    category: "scientific",
    age: "medieval",
    cost: 150,
    description: "Étudie les astres, source de prestige savant.",
    effects: { prestige: 4, stability: 1 },
  },
  universite: {
    id: "universite",
    name: "Université",
    category: "scientific",
    age: "steam",
    cost: 220,
    description: "Forme les esprits qui feront entrer Orion dans une ère nouvelle.",
    effects: { populationGrowth: 0.015, gold: 6 },
  },
  centre_recherche: {
    id: "centre_recherche",
    name: "Centre de recherche",
    category: "scientific",
    age: "modern",
    cost: 300,
    description: "Accélère considérablement le progrès technologique du royaume.",
    effects: { gold: 10, prestige: 5 },
  },
  centre_spatial: {
    id: "centre_spatial",
    name: "Centre spatial",
    category: "scientific",
    age: "future",
    cost: 380,
    description: "Étudie les étoiles et prépare la conquête d'Orion tout entier.",
    effects: { prestige: 12, gold: 10 },
  },

  // --- Culturel : foi, mémoire et grandeur ---
  temple: {
    id: "temple",
    name: "Temple",
    category: "cultural",
    age: "medieval",
    cost: 70,
    description: "Améliore la stabilité et la piété du royaume.",
    effects: { stability: 4, prestige: 1 },
  },
  museum: {
    id: "museum",
    name: "Musée",
    category: "cultural",
    age: "medieval",
    cost: 130,
    description: "Expose les trésors du royaume, source de prestige.",
    effects: { prestige: 6 },
  },
  monument: {
    id: "monument",
    name: "Monument",
    category: "cultural",
    age: "medieval",
    cost: 210,
    description: "Un monument grandiose célébrant la dynastie.",
    effects: { prestige: 9, stability: 2 },
  },
  grand_theatre: {
    id: "grand_theatre",
    name: "Grand Théâtre",
    category: "cultural",
    age: "steam",
    cost: 200,
    description: "Les arts fleurissent à l'ère de l'industrie.",
    effects: { prestige: 10, stability: 1 },
  },
  opera: {
    id: "opera",
    name: "Opéra national",
    category: "cultural",
    age: "modern",
    cost: 260,
    description: "Le rayonnement culturel du royaume dépasse ses frontières.",
    effects: { prestige: 14 },
  },
  archives_numeriques: {
    id: "archives_numeriques",
    name: "Archives numériques",
    category: "cultural",
    age: "future",
    cost: 340,
    description: "Toute l'histoire d'Orion préservée pour l'éternité.",
    effects: { prestige: 18, stability: 1 },
  },

  // --- Politique : pouvoir et diplomatie ---
  hall: {
    id: "hall",
    name: "Grande Halle",
    category: "political",
    age: "medieval",
    cost: 90,
    description: "Un lieu de pouvoir qui accroît le prestige.",
    effects: { prestige: 3, stability: 1 },
  },
  parliament: {
    id: "parliament",
    name: "Parlement",
    category: "political",
    age: "medieval",
    cost: 180,
    description: "Une assemblée qui stabilise la gouvernance du royaume.",
    effects: { stability: 9 },
  },
  embassy: {
    id: "embassy",
    name: "Ambassade",
    category: "political",
    age: "medieval",
    cost: 145,
    description: "Entretient des relations suivies avec tous les royaumes voisins.",
    effects: { relationBonus: 1 },
  },
  palace: {
    id: "palace",
    name: "Palais royal",
    category: "political",
    age: "medieval",
    cost: 260,
    description: "Le siège éclatant du pouvoir dynastique.",
    effects: { prestige: 11, stability: 3 },
  },
  chambre_industrielle: {
    id: "chambre_industrielle",
    name: "Chambre industrielle",
    category: "political",
    age: "steam",
    cost: 230,
    description: "Organise le dialogue entre le trône et les nouvelles élites industrielles.",
    effects: { stability: 11, prestige: 2 },
  },
  ministere: {
    id: "ministere",
    name: "Ministère",
    category: "political",
    age: "modern",
    cost: 290,
    description: "Une administration moderne pour gouverner un royaume complexe.",
    effects: { stability: 14 },
  },
  ia_gouvernementale: {
    id: "ia_gouvernementale",
    name: "IA gouvernementale",
    category: "political",
    age: "future",
    cost: 400,
    description: "Une intelligence artificielle assiste le trône dans chacune de ses décisions.",
    effects: { stability: 20, prestige: 4 },
  },
};

export const RECRUIT_BATCH = 25;
export const RECRUIT_COST_PER_MAN = 3;

export const UNIT_TYPES: UnitTypeDef[] = [
  {
    id: "infantry",
    name: "Infanterie",
    corps: "land",
    age: "medieval",
    description: "Fantassins équipés d'épées et de boucliers.",
    equipCostPerMan: 6,
    upkeepPerMan: 0.3,
    power: 1,
    requiresBuilding: "barracks",
  },
  {
    id: "cavalry",
    name: "Cavalerie",
    corps: "land",
    age: "medieval",
    description: "Cavaliers rapides, redoutables en charge.",
    equipCostPerMan: 16,
    upkeepPerMan: 0.7,
    power: 2.6,
    requiresBuilding: "barracks",
  },
  {
    id: "galley",
    name: "Galère de guerre",
    corps: "naval",
    age: "medieval",
    description: "Navire de guerre armé d'éperons et d'archers.",
    equipCostPerMan: 30,
    upkeepPerMan: 1.2,
    power: 4,
    requiresBuilding: "shipyard",
  },
  {
    id: "transport",
    name: "Knarr de transport",
    corps: "naval",
    age: "medieval",
    description: "Navire robuste pour le transport de troupes et de marchandises.",
    equipCostPerMan: 18,
    upkeepPerMan: 0.6,
    power: 1.5,
    requiresBuilding: "shipyard",
  },
  {
    id: "artillery",
    name: "Artillerie à vapeur",
    corps: "land",
    age: "steam",
    description: "Canons tractés à vapeur, redoutables lors des sièges.",
    equipCostPerMan: 26,
    upkeepPerMan: 1,
    power: 5,
    requiresBuilding: "arsenal_vapeur",
  },
  {
    id: "ironclad",
    name: "Cuirassé",
    corps: "naval",
    age: "steam",
    description: "Navire blindé propulsé à la vapeur, dominant les mers.",
    equipCostPerMan: 42,
    upkeepPerMan: 1.6,
    power: 7,
    requiresBuilding: "shipyard",
  },
  {
    id: "tank",
    name: "Char de combat",
    corps: "land",
    age: "modern",
    description: "Blindé moderne capable de percer n'importe quel front.",
    equipCostPerMan: 60,
    upkeepPerMan: 2.2,
    power: 9,
    requiresBuilding: "arsenal_vapeur",
  },
  {
    id: "fighter",
    name: "Avion de chasse",
    corps: "air",
    age: "modern",
    description: "Premier appareil du corps aérien, maître du ciel d'Orion.",
    equipCostPerMan: 70,
    upkeepPerMan: 2.6,
    power: 8,
    requiresBuilding: "aeroport",
  },
  {
    id: "carrier",
    name: "Porte-avions",
    corps: "naval",
    age: "modern",
    description: "Projette la puissance aérienne au-delà des océans.",
    equipCostPerMan: 90,
    upkeepPerMan: 3.2,
    power: 12,
    requiresBuilding: "shipyard",
  },
  {
    id: "mech",
    name: "Méca de combat",
    corps: "land",
    age: "future",
    description: "Unité robotisée à la puissance de feu écrasante.",
    equipCostPerMan: 120,
    upkeepPerMan: 4,
    power: 14,
    requiresBuilding: "arsenal_vapeur",
  },
  {
    id: "orbital_ship",
    name: "Vaisseau orbital",
    corps: "air",
    age: "future",
    description: "Frappe depuis l'orbite d'Orion, hors de portée de toute défense classique.",
    equipCostPerMan: 150,
    upkeepPerMan: 5,
    power: 20,
    requiresBuilding: "aeroport",
  },
  {
    id: "sub",
    name: "Sous-marin nucléaire",
    corps: "naval",
    age: "future",
    description: "Silencieux et redoutable, il patrouille sans jamais être détecté.",
    equipCostPerMan: 130,
    upkeepPerMan: 4.5,
    power: 16,
    requiresBuilding: "shipyard",
  },
];

export const MALE_NAMES = [
  "Aldric", "Baldwin", "Cedric", "Dagobert", "Edric", "Fenwick", "Gareth",
  "Halvard", "Ivor", "Joran", "Kendrick", "Leofric", "Magnus", "Norbert",
  "Osric", "Perceval", "Quentin", "Roderic", "Sigurd", "Théobald", "Ulric",
  "Vidar", "Wilfrid", "Yorick", "Alaric", "Brannor",
];

export const FEMALE_NAMES = [
  "Adelinde", "Bertha", "Clothilde", "Dagny", "Elswyth", "Freya", "Gisela",
  "Hilda", "Iseult", "Jorunn", "Kunigunde", "Liuba", "Mahaut", "Nissa",
  "Odile", "Petronille", "Ragnhild", "Sunniva", "Théodora", "Ursule",
  "Valdis", "Winifred", "Ysolde", "Aveline", "Berengère",
];

export const NEIGHBOR_NAME_POOL = [
  "Varnheim", "Castelmoor", "Thornwatch", "Ravensholt", "Duskvale",
  "Ostmark", "Brackenfeld", "Sylvamont", "Grimhold", "Aldenreach",
];

export const KINGDOM_NAME_ADJ = [
  "Val", "Mont", "Brise", "Roche", "Champs", "Bois", "Source", "Rive",
];
export const KINGDOM_NAME_SUFFIX = [
  "fort", "brise", "combe", "garde", "haven", "roche", "val", "terre",
];

export const EXPLORER_TITLES_MALE = [
  "Capitaine", "Éclaireur", "Navigateur", "Cartographe", "Baroudeur",
];
export const EXPLORER_TITLES_FEMALE = [
  "Capitaine", "Éclaireuse", "Navigatrice", "Cartographe", "Baroudeuse",
];
export const MERCHANT_TITLES_MALE = ["Négociant", "Marchand", "Facteur"];
export const MERCHANT_TITLES_FEMALE = ["Négociante", "Marchande", "Factrice"];
export const PROSPECTOR_TITLES_MALE = ["Prospecteur", "Mineur", "Arpenteur"];
export const PROSPECTOR_TITLES_FEMALE = ["Prospectrice", "Mineuse", "Arpenteuse"];
