export interface CampagneMarketing {
  id: string
  nom: string
  description: string
  palier: 1 | 2 | 3 | 4
  cout: number
  gainFans: number
  gainPopularite: number
  fansRequis: number
  cooldownSemaines: number
}

export const PALIERS_MARKETING: Record<number, string> = {
  1: "Locale",
  2: "Régionale",
  3: "Nationale",
  4: "Internationale",
}

export const CAMPAGNES_MARKETING: CampagneMarketing[] = [
  // Palier 1 — Locale
  {
    id: "flyers",
    nom: "Distribution de flyers",
    description: "Des bénévoles distribuent des flyers en centre-ville.",
    palier: 1,
    cout: 200,
    gainFans: 40,
    gainPopularite: 0,
    fansRequis: 0,
    cooldownSemaines: 1,
  },
  {
    id: "affichage-sauvage",
    nom: "Affichage sauvage dans le quartier",
    description: "Des affiches collées un peu partout autour de la salle.",
    palier: 1,
    cout: 350,
    gainFans: 70,
    gainPopularite: 1,
    fansRequis: 0,
    cooldownSemaines: 1,
  },
  {
    id: "post-sponsorise",
    nom: "Post sponsorisé sur les réseaux sociaux",
    description: "Une petite campagne ciblée sur les réseaux sociaux.",
    palier: 1,
    cout: 300,
    gainFans: 90,
    gainPopularite: 1,
    fansRequis: 0,
    cooldownSemaines: 1,
  },
  {
    id: "stand-marche",
    nom: "Stand sur un marché local",
    description: "Un stand tenu par des catcheurs de la fédération un samedi matin.",
    palier: 1,
    cout: 500,
    gainFans: 120,
    gainPopularite: 1,
    fansRequis: 0,
    cooldownSemaines: 2,
  },
  {
    id: "partenariat-bar",
    nom: "Partenariat avec un bar sportif",
    description: "Les shows sont diffusés dans un bar sportif du coin.",
    palier: 1,
    cout: 650,
    gainFans: 150,
    gainPopularite: 2,
    fansRequis: 0,
    cooldownSemaines: 2,
  },

  // Palier 2 — Régionale
  {
    id: "radio-locale",
    nom: "Spot publicitaire sur une radio locale",
    description: "Un spot diffusé plusieurs fois par jour sur une radio de la région.",
    palier: 2,
    cout: 1200,
    gainFans: 350,
    gainPopularite: 2,
    fansRequis: 1500,
    cooldownSemaines: 3,
  },
  {
    id: "presse-regionale",
    nom: "Interview dans la presse régionale",
    description: "Un journaliste local consacre un article à la fédération.",
    palier: 2,
    cout: 1000,
    gainFans: 300,
    gainPopularite: 2,
    fansRequis: 1500,
    cooldownSemaines: 3,
  },
  {
    id: "sponsoring-club",
    nom: "Sponsoring d'un club sportif local",
    description: "Le logo de la fédération apparaît sur les maillots d'un club local.",
    palier: 2,
    cout: 1800,
    gainFans: 450,
    gainPopularite: 3,
    fansRequis: 2500,
    cooldownSemaines: 4,
  },
  {
    id: "affichage-regional",
    nom: "Campagne d'affichage régional",
    description: "Des panneaux publicitaires dans plusieurs villes de la région.",
    palier: 2,
    cout: 2200,
    gainFans: 550,
    gainPopularite: 3,
    fansRequis: 3000,
    cooldownSemaines: 4,
  },
  {
    id: "chaine-youtube",
    nom: "Lancement d'une chaîne YouTube dédiée",
    description: "Highlights et coulisses publiés chaque semaine.",
    palier: 2,
    cout: 1500,
    gainFans: 600,
    gainPopularite: 2,
    fansRequis: 3000,
    cooldownSemaines: 4,
  },

  // Palier 3 — Nationale
  {
    id: "tv-regionale",
    nom: "Publicité sur une chaîne de télé régionale",
    description: "Un spot télévisé diffusé aux heures de grande écoute régionale.",
    palier: 3,
    cout: 4000,
    gainFans: 1200,
    gainPopularite: 4,
    fansRequis: 8000,
    cooldownSemaines: 5,
  },
  {
    id: "magazine-national",
    nom: "Article dans un magazine spécialisé national",
    description: "Un grand dossier consacré à la fédération et ses lutteurs.",
    palier: 3,
    cout: 3500,
    gainFans: 1000,
    gainPopularite: 4,
    fansRequis: 8000,
    cooldownSemaines: 5,
  },
  {
    id: "marque-sport",
    nom: "Partenariat avec une marque de sport",
    description: "Un équipementier sponsorise les tenues des catcheurs vedettes.",
    palier: 3,
    cout: 5500,
    gainFans: 1600,
    gainPopularite: 5,
    fansRequis: 12000,
    cooldownSemaines: 6,
  },
  {
    id: "tele-realite",
    nom: "Passage dans une émission de télé-réalité",
    description: "Deux catcheurs de la fédération participent à une émission populaire.",
    palier: 3,
    cout: 6500,
    gainFans: 2000,
    gainPopularite: 5,
    fansRequis: 14000,
    cooldownSemaines: 6,
  },
  {
    id: "affichage-national",
    nom: "Campagne d'affichage national",
    description: "Des panneaux publicitaires dans les grandes villes du pays.",
    palier: 3,
    cout: 8000,
    gainFans: 2400,
    gainPopularite: 6,
    fansRequis: 16000,
    cooldownSemaines: 6,
  },

  // Palier 4 — Internationale
  {
    id: "tv-prime-time",
    nom: "Publicité télé nationale en prime time",
    description: "Un spot diffusé pendant les programmes les plus regardés du pays.",
    palier: 4,
    cout: 15000,
    gainFans: 4500,
    gainPopularite: 8,
    fansRequis: 25000,
    cooldownSemaines: 8,
  },
  {
    id: "influenceur-international",
    nom: "Partenariat avec un influenceur international",
    description: "Une star des réseaux sociaux met en avant la fédération auprès de millions d'abonnés.",
    palier: 4,
    cout: 18000,
    gainFans: 5500,
    gainPopularite: 8,
    fansRequis: 30000,
    cooldownSemaines: 8,
  },
  {
    id: "plateforme-streaming",
    nom: "Diffusion des shows sur une plateforme de streaming",
    description: "Les shows sont désormais accessibles en direct sur une grande plateforme.",
    palier: 4,
    cout: 22000,
    gainFans: 7000,
    gainPopularite: 10,
    fansRequis: 35000,
    cooldownSemaines: 9,
  },
  {
    id: "serie-documentaire",
    nom: "Série documentaire sur une grosse plateforme de streaming",
    description: "Une série documentaire suit les coulisses de la fédération, saison après saison.",
    palier: 4,
    cout: 35000,
    gainFans: 12000,
    gainPopularite: 12,
    fansRequis: 45000,
    cooldownSemaines: 10,
  },
  {
    id: "tournee-mondiale",
    nom: "Tournée mondiale médiatique",
    description: "Une tournée promotionnelle internationale, relayée par les plus gros médias.",
    palier: 4,
    cout: 45000,
    gainFans: 16000,
    gainPopularite: 15,
    fansRequis: 55000,
    cooldownSemaines: 10,
  },
]
